#!/usr/bin/env node
//
// Vendors a design's webfonts into its theme.css as base64 woff2.
//
// Why this exists
// ---------------
// The kitchen sinks used to pull their fonts from fonts.googleapis.com with a
// <link>. That has the same problem vendor/README.md describes for a floating
// CDN build of Tailwind — the same commit renders differently depending on when
// and where you open it — and one more besides: a design whose typeface only
// arrives over the network is a design that silently degrades to the system
// sans on any device that cannot reach Google, which is how "the headings look
// wrong on my phone" happens while the laptop looks fine.
//
// theme.css is the only file a kitchen sink loads besides the vendored
// compiler (see CLAUDE.md), and it is written to be pasted verbatim into a
// consuming project. So the fonts go inside it, as data URIs, rather than
// alongside it as .woff2 files — a relative url() would break both of those
// properties at once.
//
// The cost is size: a theme.css with fonts in it runs 100–350KB rather than
// 10KB. That is the deliberate trade. A consuming project that would rather
// serve the files itself can delete the @font-face block — the tokens below it
// name the families and nothing else depends on it.
//
// Usage
// -----
//   node scripts/vendor-fonts.mjs            # re-vendor every design in FONTS
//   node scripts/vendor-fonts.mjs playful    # just one
//
// Re-running is idempotent: the block is delimited by the two markers below and
// is replaced wholesale, so an upgrade is a reviewable diff rather than an
// append.

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// Google's css2 endpoint serves woff2 only to a browser-ish UA; with the
// default Node UA it hands back much larger truetype.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Only these subsets are vendored. Google's <link> offered every subset it has
// (cyrillic, greek, vietnamese…) and let the browser download what the page
// touched; vendoring forces the choice up front, and latin + latin-ext is what
// keeps accented Western European text rendering as it does today. Adding a
// subset here roughly doubles the weight of the block it lands in.
const SUBSETS = ["latin", "latin-ext"];

const BEGIN = "/* === vendored fonts: begin — generated by scripts/vendor-fonts.mjs === */";
const END = "/* === vendored fonts: end === */";

// Weight ranges are requested as variable axes (`400..700`) rather than as a
// list of static weights: one file per family covers every weight the design
// uses, and it is smaller than the statics it replaces.
const FONTS = {
  learn: {
    // Baloo 2 stands in for the reference product's own rounded face, which is
    // proprietary. It is the substitute that reaches weight 800 — this design
    // sets buttons, headings and navigation there, and most openly-licensed
    // rounded faces stop at 700.
    query: "family=Baloo+2:wght@400..800",
    licences: ["Baloo 2 — SIL Open Font License 1.1"],
  },
  slate: {
    query: "family=Inter:wght@400..700&family=JetBrains+Mono:wght@400..500",
    licences: ["Inter — SIL Open Font License 1.1", "JetBrains Mono — SIL Open Font License 1.1"],
  },
  "warm-paper": {
    query:
      "family=Crimson+Pro:wght@400..600&family=Inter:wght@400..600&family=JetBrains+Mono:wght@400..500",
    licences: [
      "Crimson Pro — SIL Open Font License 1.1",
      "Inter — SIL Open Font License 1.1",
      "JetBrains Mono — SIL Open Font License 1.1",
    ],
  },
  "material-design": {
    query: "family=Roboto:wght@300..700&family=Roboto+Mono:wght@400..500",
    licences: ["Roboto — Apache License 2.0", "Roboto Mono — Apache License 2.0"],
  },
  playful: {
    query: "family=DM+Sans:wght@400..700&family=Fredoka:wght@600..700",
    licences: ["DM Sans — SIL Open Font License 1.1", "Fredoka — SIL Open Font License 1.1"],
  },
};

const get = async (url, as) => {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${url} → ${res.status} ${res.statusText}`);
  return as === "buffer" ? Buffer.from(await res.arrayBuffer()) : res.text();
};

async function vendor(design) {
  const { query, licences } = FONTS[design];
  const css = await get(`https://fonts.googleapis.com/css2?${query}&display=swap`);

  // Each @font-face in Google's response is preceded by a /* subset */ comment,
  // which is the only place the subset name appears.
  const faces = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)];
  if (!faces.length) throw new Error(`${design}: no @font-face blocks in the Google Fonts response`);

  const out = [];
  let bytes = 0;
  for (const [, subset, body] of faces) {
    if (!SUBSETS.includes(subset)) continue;
    const field = (name) => new RegExp(`${name}:\\s*([^;]+);`).exec(body)?.[1].trim();
    const url = /url\((https:[^)]+)\)/.exec(body)?.[1];
    if (!url) throw new Error(`${design}: a ${subset} face has no url()`);
    const woff2 = await get(url, "buffer");
    bytes += woff2.length;
    out.push(
      [
        `@font-face {`,
        `  font-family: ${field("font-family")};`,
        `  font-style: ${field("font-style")};`,
        `  font-weight: ${field("font-weight")};`,
        `  font-display: swap;`,
        `  src: url("data:font/woff2;base64,${woff2.toString("base64")}") format("woff2");`,
        `  unicode-range: ${field("unicode-range")};`,
        `}`,
      ].join("\n")
    );
  }
  if (!out.length) throw new Error(`${design}: none of ${SUBSETS.join(", ")} matched`);

  const header = [
    BEGIN,
    `/*`,
    ` * Vendored so the design renders the same everywhere, including on a device`,
    ` * that cannot reach fonts.googleapis.com. Subsets: ${SUBSETS.join(", ")}.`,
    ` * Regenerate with: node scripts/vendor-fonts.mjs ${design}`,
    ` *`,
    ...licences.map((l) => ` * ${l}`),
    ` */`,
  ].join("\n");
  const block = `${header}\n\n${out.join("\n\n")}\n\n${END}`;

  const path = join(ROOT, "designs", design, "theme.css");
  const src = readFileSync(path, "utf8");
  let next;
  if (src.includes(BEGIN)) {
    next = src.replace(new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`), block);
  } else {
    // Ahead of :root, so the faces are declared before anything references them.
    const anchor = src.indexOf(":root {");
    if (anchor < 0) throw new Error(`${design}: theme.css has no :root block to insert before`);
    next = src.slice(0, anchor) + block + "\n\n" + src.slice(anchor);
  }
  writeFileSync(path, next);
  console.log(
    `${design.padEnd(17)} ${out.length} face(s), ${(bytes / 1024).toFixed(0)}KB woff2 → ` +
      `theme.css is now ${(Buffer.byteLength(next) / 1024).toFixed(0)}KB`
  );
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const requested = process.argv.slice(2);
const targets = requested.length ? requested : Object.keys(FONTS);
for (const t of targets) {
  if (!FONTS[t]) {
    console.error(`unknown design "${t}" — known: ${Object.keys(FONTS).join(", ")}`);
    process.exit(1);
  }
  await vendor(t);
}
